// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
  [DbContext(typeof(DataContext))]
  [Migration("20201006215121_ActivityLikes")]
  partial class ActivityLikes
  {
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
          .HasAnnotation("ProductVersion", "3.0.0");

      modelBuilder.Entity("Domain.ActivityLikes", b =>
          {
            b.Property<Guid>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("TEXT");

            b.Property<Guid>("Comment_Id")
                      .HasColumnType("TEXT");

            b.Property<Guid>("User_Id")
                      .HasColumnType("TEXT");

            b.HasKey("Id");

            b.ToTable("ActivityLikes");
          });
#pragma warning restore 612, 618
    }
  }
}
