// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
  [DbContext(typeof(DataContext))]
  [Migration("20201006215054_Follows")]
  partial class Follows
  {
    public Guid Id { get; set; }
    public Guid UserId { get; set; }
    public Guid FollowerId { get; set; }
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
          .HasAnnotation("ProductVersion", "3.0.0");

      modelBuilder.Entity("Domain.Follows", b =>
          {
            b.Property<Guid>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("TEXT");

            b.Property<Guid>("User_Id")
                      .HasColumnType("TEXT");

            b.Property<Guid>("Follower_Id")
                      .HasColumnType("TEXT");

            b.HasKey("Id");

            b.ToTable("Follows");
          });
#pragma warning restore 612, 618
    }
  }
}
