// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
  [DbContext(typeof(DataContext))]
  [Migration("20201006213440_Activities")]
  partial class Activities
  {
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
          .HasAnnotation("ProductVersion", "3.0.0");

      modelBuilder.Entity("Domain.Activity", b =>
          {
            b.Property<Guid>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("TEXT");

            b.Property<string>("Title")
                      .HasColumnType("TEXT");

            b.Property<string>("Body")
                      .HasColumnType("TEXT");

            b.Property<string>("Subject")
                      .HasColumnType("TEXT");

            b.Property<string>("DateTimeCreated")
                      .HasColumnType("TEXT");

            b.HasKey("Id");

            b.ToTable("Activities");
          });
#pragma warning restore 612, 618
    }
  }
}
