// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
  [DbContext(typeof(DataContext))]
  [Migration("20201006215040_ActivityComments")]
  partial class ActivityComments
  {
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
          .HasAnnotation("ProductVersion", "3.0.0");

      modelBuilder.Entity("Domain.ActivityComment", b =>
          {
            b.Property<Guid>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("TEXT");

            b.Property<Guid>("Activity_Id")
                      .HasColumnType("TEXT");

            b.Property<Guid>("User_Id")
                      .HasColumnType("TEXT");

            b.Property<string>("Comment")
                      .HasColumnType("TEXT");

            b.Property<DateTime>("DateTime_Created")
                      .HasColumnType("TEXT");

            b.Property<DateTime>("DateTime_Edited")
                      .HasColumnType("TEXT");

            b.HasKey("Id");

            b.ToTable("ActivityComments");
          });
#pragma warning restore 612, 618
    }
  }
}
