// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
  [DbContext(typeof(DataContext))]
  [Migration("20201006215108_ActivityRaiting")]
  partial class ActivityRaiting
  {
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
          .HasAnnotation("ProductVersion", "3.0.0");

      modelBuilder.Entity("Domain.ActiviyRaiting", b =>
          {
            b.Property<Guid>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("TEXT");

            b.Property<Guid>("User_Id")
                      .HasColumnType("TEXT");

            b.Property<Guid>("Activity_ID")
                      .HasColumnType("TEXT");

            b.Property<float>("Raiting")
                      .HasColumnType("FLOAT");

            b.HasKey("Id");

            b.ToTable("ActivityRaiting");
          });
#pragma warning restore 612, 618
    }
  }
}
